# Generated by Django 3.2.11 on 2023-12-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0004_alter_schedule_id_alter_schedulemanager_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleManager',
        ),
        migrations.RemoveField(
            model_name='userschedule',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='userschedule',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserScheduleManager',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='UserSchedule',
        ),
    ]
