# Generated by Django 4.2.9 on 2024-02-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='aadhar',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
