# Generated by Django 4.2.9 on 2024-02-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0002_booking_aadhar_booking_address_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
