# Generated by Django 4.2.9 on 2024-02-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0003_booking_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='gst',
        ),
    ]
