# Generated by Django 4.2.9 on 2024-02-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0004_remove_booking_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkout_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
