# Generated by Django 4.2.4 on 2023-09-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisonapp', '0003_auto_20180808_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
