# Generated by Django 3.2.11 on 2023-12-06 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bisonapp', '0004_alter_tsuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tsuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
